/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class avrBridgeJavaDev_avr */

#ifndef _Included_avrBridgeJavaDev_avr
#define _Included_avrBridgeJavaDev_avr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_avrBridgeJavaDev_avr_test
  (JNIEnv *, jobject);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    getStatus
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_avrBridgeJavaDev_avr_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    setPort
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_setPort
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    setPortPin
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_setPortPin
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    setPortPinDir
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_setPortPinDir
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    getPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_getPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    getPortPin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_getPortPin
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    getAdc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_getAdc
  (JNIEnv *, jobject, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    setDac
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_setDac
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     avrBridgeJavaDev_avr
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_avrBridgeJavaDev_avr_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
